export const NOTATIONS = [
  ['UML', 'DESIGN'],
  ['ERD', 'DESIGN'],
  ['Structured Design', 'DESIGN'],
  ['DFD', 'DESIGN'],
  ['Java', 'CODE'],
  ['Python', 'CODE'],
  ['C', 'CODE'],
  ['C++', 'CODE'],
  ['JavaScript', 'CODE'],
  ['TypeScript', 'CODE'],
] as const

/** [name, kind, notation, category, keywords, description] */
export const DEMO_COMPONENTS = [
  [
    'Observer pattern class diagram',
    'DESIGN',
    'UML',
    'Behavioural patterns',
    ['observer', 'event', 'publish-subscribe'],
    'UML class diagram of the Observer pattern with Subject and Observer interfaces.',
  ],
  [
    'Strategy pattern class diagram',
    'DESIGN',
    'UML',
    'Behavioural patterns',
    ['strategy', 'algorithm', 'polymorphism'],
    'Interchangeable algorithms behind a common Strategy interface.',
  ],
  [
    'Singleton in Java',
    'CODE',
    'Java',
    'Creational patterns',
    ['singleton', 'lazy', 'thread-safe'],
    'Thread-safe lazily initialised singleton using the holder idiom.',
  ],
  [
    'Builder in TypeScript',
    'CODE',
    'TypeScript',
    'Creational patterns',
    ['builder', 'fluent', 'immutable'],
    'Fluent builder producing immutable objects.',
  ],
  [
    'Adapter pattern class diagram',
    'DESIGN',
    'UML',
    'Structural patterns',
    ['adapter', 'wrapper', 'interface'],
    'Object adapter converting one interface into another.',
  ],
  [
    'CSV parser',
    'CODE',
    'Python',
    'Parsing',
    ['csv', 'parser', 'stream'],
    'Streaming RFC 4180 CSV parser with quoted field support.',
  ],
  [
    'JSON tokenizer',
    'CODE',
    'C',
    'Parsing',
    ['json', 'tokenizer', 'parser'],
    'Allocation-free JSON tokenizer.',
  ],
  [
    'Merge sort',
    'CODE',
    'C++',
    'Sorting and searching',
    ['sort', 'merge', 'stable'],
    'Stable O(n log n) merge sort on iterators.',
  ],
  [
    'Binary search',
    'CODE',
    'Java',
    'Sorting and searching',
    ['search', 'binary', 'array'],
    'Generic binary search over sorted arrays.',
  ],
  [
    'Library system ERD',
    'DESIGN',
    'ERD',
    'Data processing',
    ['library', 'entity', 'relationship'],
    'Entities and relationships for a lending library.',
  ],
  [
    'Order processing DFD',
    'DESIGN',
    'DFD',
    'Data processing',
    ['order', 'data-flow', 'context'],
    'Level-0 and level-1 data flow diagrams for order processing.',
  ],
  [
    'Login form widget',
    'CODE',
    'JavaScript',
    'UI widgets',
    ['form', 'login', 'validation'],
    'Accessible login form with client-side validation.',
  ],
  [
    'JWT auth middleware',
    'CODE',
    'TypeScript',
    'Authentication',
    ['jwt', 'auth', 'middleware'],
    'Express middleware verifying Bearer JWTs.',
  ],
  [
    'Payroll structure chart',
    'DESIGN',
    'Structured Design',
    'Data processing',
    ['payroll', 'structure-chart', 'modules'],
    'Structure chart decomposing a payroll system into modules.',
  ],
] as const
